### ISSUE TITLE
Deployment fails

### ISSUE THREAD

**Issue by ToyMakerGR** [Azure-Samples/dotNET-FrontEnd-to-BackEnd-with-DAPR-on-Azure-Container-Apps#5]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I just followed the guide to deploy the app. While all steps worked, the very last action (Deploy Container Apps) fails with the message:
"ERROR: Failed to retrieve credentials for container registry. Please provide the registry username and password
Error: Error: az cli script failed.
cleaning up container..."

### Any log messages given by the failure
> Starting script execution via docker image mcr.microsoft.com/azure-cli:2.38.0
WARNING: The command requires the extension containerapp. It will be installed first.
WARNING: The installed extension 'containerapp' is in preview.
WARNING: No credential was provided to access Azure Container Registry. Trying to look up...
ERROR: Failed to retrieve credentials for container registry. Please provide the registry username and password
Error: Error: az cli script failed.
cleaning up container...
MICROSOFT_AZURE_CLI_1659386309650_CONTAINER
(node:2159) UnhandledPromiseRejectionWarning: Error: az cli script failed.
    at /home/runner/work/_actions/azure/CLI/v1/dist/index.js:1:[23](https://github.com/ToyMakerGR/Azure_container_dapr/runs/7619560921?check_suite_focus=true#step:6:24)964
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/azure/CLI/v1/dist/index.js:1:204[36](https://github.com/ToyMakerGR/Azure_container_dapr/runs/7619560921?check_suite_focus=true#step:6:37))
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2159) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2159) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ToyMakerGR** [comment]
Update:
suddenly today everything worked as expected from zero changes from my side. I have tried another repo among the container app series - https://github.com/Azure-Samples/dotNET-FrontEnd-to-BackEnd-on-Azure-Container-Apps, was still not working until yesterday, all of a sudden both worked end-to-end. I tried different container names, different regions, all deployments work fine.

A detail: the log, after the "WARNING: No credential was provided to access Azure Container Registry. Trying to look up...", instead of getting the error, now I get "WARNING: Adding registry password as a secret with name "*****acrazurecrio-*****acr"". Deployment worked until the end after that.

I'd really like to learn more about this - a docs pointer or something - and why / how this error occurred. Thank you in advance.

**Comment by ToyMakerGR** [comment]
Update #2: the failed behavior described in the original post returned.
I don't know what to make out of this one.

**Comment by cwhakes** [comment]
I ran across this issue while trying to troubleshoot a similar one of my own. I was able to move past it by enabling "Admin User" under "Access Keys" within my container registry.
